version: '3.4'
services:

  #PHP Service
  grofreshapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: grofresh-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - grofresh-network

  #Nginx Service
  grofreshwebservice:
    image: nginx:alpine
    container_name: grofresh-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "81:80"
      - "449:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - grofresh-network

  #MySQL Service
  grofreshdb:
    image: mysql:5.7
    container_name: grofresh-db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes
      MYSQL_DATABASE: 6valy_db
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      # - ./installation:/docker-entrypoint-initdb.d
      - dbdata2:/var/lib/mysql/
    #network_mode: "host"
    networks:
      - grofresh-network

#Docker Networks
networks:
  grofresh-network:
    driver: bridge
#Volumes
volumes:
  dbdata2:
    driver: local
